s;    G4INCLUDE=.*;    G4INCLUDE=\"${BELLE2_EXTERNALS_DIR}/include/geant4\";g
s;    G4LIB=.*;    G4LIB=\"${BELLE2_EXTERNALS_DIR}/lib/\${BELLE2_EXTERNALS_SUBDIR}\";g
s;setenv G4INCLUDE .*;setenv G4INCLUDE \"${BELLE2_EXTERNALS_DIR}/geant4/include\";g
s;setenv G4LIB .*;setenv G4LIB \"${BELLE2_EXTERNALS_DIR}/lib/\${BELLE2_EXTERNALS_SUBDIR}\";g
