[workspace]
channels = ["conda-forge"]
name = "basf2-externals"
platforms = ["linux-64"]
channel-priority = "disabled"

[tasks]

[dependencies]
astyle = "3.1.*"
bazel = "2.0.0.*"
binutils = "2.46.*"
bzip2 = "1.0.8.*"
clhep = "2.4.7.2.*"
cppcheck = "2.20.0.*"
cppzmq = "4.7.1.*"
cry = "1.7.*"
davix = "0.8.10.*"
doxygen = "1.13.2.*"
eigen = "3.4.0.*"
epics-base = "7.0.10.*"
evtgen = "2.2.3.*"
fastbdt = "5.6.*"
fastjet-cxx = "3.5.1.*"
fftw = "3.3.11.*"
frugally-deep = "0.15.19.*"
functionalplus = "0.2.18.*"
gcc = "14.3.*"
geant4 = "11.4.1.*"
gfortran = "14.3.*"
git = "2.52.0.*"
git-lfs = "3.7.1.*"
gmp = "6.3.0.*"
gsl = "2.7.*"
gtest = "1.17.0.*"
gxx = "14.3.*"
hammer = "1.4.1.*"
hdf5 = "1.14.6.*"
hepmc2 = "2.6.11.*"
isl = "0.27.*"
jemalloc = "5.2.1.*"
lhapdf = "6.5.6.*"
libboost-devel = "1.90.*"
libffi = "3.5.2.*"
libuuid = "2.41.3.*"
libxml2 = "2.15.1.*"
libxslt = "1.1.43.*"
lz4-c = "1.10.0.*"
millepede = "4.16.3.*"
mpc = "1.2.1.*"
mpfr = "4.2.2.*"
nlohmann_json = "3.12.0.*"
onnxruntime-cpp = "1.24.2.*"
pandoc = "2.12.*"
photos = "3.64.*"
pkg-config = "0.29.2.*"
libpqxx = "8.0.*"
pythia8 = "8.312.*"
python = "3.12.*"
pytorch = "2.1.2.*"
rave = "0.6.25.*"
rclone = "1.54.1.*"
root_base = "6.36.10.*"
roounfold = "3.1.0.*"
scons = "4.11.*"
sqlite = "3.52.0.*"
tauloa = "1.1.8.*"
tbb = "2022.3.0.*"
thepeg = "2.2.3.*"
valgrind = "3.26.0.*"
veccore = "0.8.2.*"
vecgeom = "2.0.0.*"
vector-classes = "1.4.5.*"
vgm = "5.4.*"
xrootd = "5.9.1.*"
xz = "5.8.2.*"
yaml-cpp = "0.8.0.*"
zeromq = "4.3.5.*"
zlib = "1.3.2.*"
